name: Azure CLI Login Tests
on: 
  push:
      branches:
        - main
jobs:
  build:
    runs-on: self-hosted
    steps:            
    - name: "Login Azure"
      uses: azure/CLI@v1
      with:
        azcliversion: 2.24.2
    - name: "Call CosmosDB"
      uses: actions/checkout@v3
      with:
        azcliversion: 2.24.2
        inlineScript: |
          nslookup cosmosdb-tcs-devizdb-core.documents.azure.com
