name: Azure CLI Login Tests
on: 
  push:
      branches:
        - main
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    
    - name: "Login Azure"
      uses: azure/CLI@v1
      with:
        azcliversion: 2.24.2
        inlineScript: |
          az login --identity
    
    - name: "Call CosmosDB"
      uses: azure/actions/ssh@master
      with:
        command: |
          nslookup cosmosdb-tcs-devizdb-core.documents.azure.com
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' # install the python version needed

    - name: install python packages
      run: |
        python -m pip install --upgrade pip
    - name: "Get items in cosmosdb"
      run: |
        python get_all_items.py
